server:
  port: 8848
spring:
  datasource:
    #    url: jdbc:mysql://home.smarte.tech:50003/wms?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    url: jdbc:mysql://127.0.0.1:3306/analysis?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 123456
  webflux:
    base-path: /analysis
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    local-cache-scope: statement
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_uuid
      update-strategy: ignored
      insert-strategy: ignored
    banner: false

logging:
  level:
    com:
      ymkj:
        analysis:
          repository: debug
